version: "3.7"
services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181
    networks:
      - local
    environment:
      - JMXDISABLE=true
      - ZOO_DATA_DIR=/data
      - ZOO_DATA_LOG_DIR=/datalog
      - ZOO_ADMINSERVER_ENABLED=false
    volumes:
      - "zookeeper_data:/data"
      - "zookeeper_log_data:/datalog"

  kafka:
    image: neowu/kafka:2.4.1
    ports:
      - 9092:9092
    networks:
      - local
    environment:
      - KAFKA_ARGS=--override advertised.listeners=PLAINTEXT://localhost:9092
    volumes:
      - "kafka_data:/data"
    depends_on:
      - zookeeper

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - local
    volumes:
      - "./redis/redis.conf:/etc/redis/redis.conf"

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - local
    volumes:
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/cert.pem:/etc/nginx/cert.pem"
      - "./nginx/private-key.pem:/etc/nginx/private-key.pem"

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    ports:
      - 3306:3306
    networks:
      - local
    volumes:
      - "mysql_data:/var/lib/mysql"

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - local
    volumes:
      - "mongodb_data:/data/db"
    command: ["mongod", "--replSet", "dev"]

networks:
  local:
volumes:
  zookeeper_data:
  zookeeper_log_data:
  kafka_data:
  mysql_data:
  mongodb_data:
